export const EXECUTION_PLAN_AUTHORITY = 'EXECUTION_PLAN_LOCK' as const;

export const EXECUTION_PLAN_READINESS = {
  PLAN_NOT_READY: 'PLAN_NOT_READY',
  REVISION_IN_PROGRESS: 'REVISION_IN_PROGRESS',
  READY_FOR_LOCK: 'READY_FOR_LOCK',
  LOCKED_FOR_EXECUTION: 'LOCKED_FOR_EXECUTION',
} as const;

export const EXECUTION_PLAN_BLOCKER = {
  NO_ACTIVE_BASELINE: 'NO_ACTIVE_BASELINE',
  MULTIPLE_ACTIVE_BASELINES: 'MULTIPLE_ACTIVE_BASELINES',
  EXECUTION_PLAN_DRAFT_NOT_FOUND: 'EXECUTION_PLAN_DRAFT_NOT_FOUND',
  AMBIGUOUS_EXECUTION_PLAN_CONTEXT: 'AMBIGUOUS_EXECUTION_PLAN_CONTEXT',
  ACTIVE_PROJECT_WITHOUT_LOCKED_PLAN: 'ACTIVE_PROJECT_WITHOUT_LOCKED_PLAN',
  LEGACY_ACTIVE_PROJECT_REQUIRES_PLAN_ADOPTION:
    'LEGACY_ACTIVE_PROJECT_REQUIRES_PLAN_ADOPTION',
  LOCKED_PLAN_PROJECT_NOT_ACTIVE: 'LOCKED_PLAN_PROJECT_NOT_ACTIVE',
  BASELINE_BINDING_MISMATCH: 'BASELINE_BINDING_MISMATCH',
  PROJECT_NOT_PLANNED: 'PROJECT_NOT_PLANNED',
  NO_REQUIRED_WORK_ITEMS: 'NO_REQUIRED_WORK_ITEMS',
  MISSING_WORK_ITEM_DISTRIBUTION: 'MISSING_WORK_ITEM_DISTRIBUTION',
  PLANNED_QUANTITY_INCOMPLETE: 'PLANNED_QUANTITY_INCOMPLETE',
  PLANNED_QUANTITY_EXCEEDS_BASELINE: 'PLANNED_QUANTITY_EXCEEDS_BASELINE',
  INVALID_DISTRIBUTION_WORK_ITEM: 'INVALID_DISTRIBUTION_WORK_ITEM',
  INVALID_DISTRIBUTION_DATE: 'INVALID_DISTRIBUTION_DATE',
  INVALID_DISTRIBUTION_QUANTITY: 'INVALID_DISTRIBUTION_QUANTITY',
  DISTRIBUTION_INTERVAL_OVERLAP: 'DISTRIBUTION_INTERVAL_OVERLAP',
  H2A1_WEIGHT_UNAVAILABLE: 'H2A1_WEIGHT_UNAVAILABLE',
} as const;

export type ExecutionPlanBlockerCode =
  (typeof EXECUTION_PLAN_BLOCKER)[keyof typeof EXECUTION_PLAN_BLOCKER];

export interface ExecutionPlanBlocker {
  code: ExecutionPlanBlockerCode;
  boqItemId?: string;
  expectedQuantity?: string;
  plannedQuantity?: string;
}
