export const SIMPROK_INTELLIGENCE_TOOLS = {
  READ_PROJECT_CONTEXT: 'READ_PROJECT_CONTEXT',
  READ_BOQ_STRUCTURE: 'READ_BOQ_STRUCTURE',
  SEARCH_AHSP: 'SEARCH_AHSP',
  READ_AHSP_DETAIL: 'READ_AHSP_DETAIL',
  SEARCH_BASIC_PRICE: 'SEARCH_BASIC_PRICE',
  READ_BASIC_PRICE_DETAIL: 'READ_BASIC_PRICE_DETAIL',
  READ_EF_PERMISSION: 'READ_EF_PERMISSION',
  READ_EXECUTION_CONTEXT: 'READ_EXECUTION_CONTEXT',
  READ_CANONICAL_TEMPLATE: 'READ_CANONICAL_TEMPLATE',
} as const;

export type SimprokIntelligenceTool =
  (typeof SIMPROK_INTELLIGENCE_TOOLS)[keyof typeof SIMPROK_INTELLIGENCE_TOOLS];

export const SIMPROK_INTELLIGENCE_TOOL_ALLOWLIST: readonly SimprokIntelligenceTool[] =
  Object.values(SIMPROK_INTELLIGENCE_TOOLS);

export function isAllowedIntelligenceTool(
  toolName: string,
): toolName is SimprokIntelligenceTool {
  return SIMPROK_INTELLIGENCE_TOOL_ALLOWLIST.includes(
    toolName as SimprokIntelligenceTool,
  );
}
