-- IQL-01 — GOVERNED EXACT-QUESTION LEARNING MEMORY.
--
-- Additive only: one new enum, one new table, its indexes and foreign keys onto
-- tables that already exist (workspaces, resource_catalogs, observed_resources,
-- accounts). No existing table, column, or row is altered.
--
-- A sibling of ahsp_resource_identity_decisions (GHX-01) for a different subject:
-- one EXACTLY identical resource question inside one workspace. A TEACH is a
-- learning CANDIDATE and never effective; only an APPROVE by a different account
-- makes it reusable, and only through the existing Resource Identity kernel.
--
-- Sections 1-2 are the SQL generated by
--   prisma migrate diff --from-schema-datamodel <HEAD schema> \
--                       --to-schema-datamodel prisma/schema.prisma --script
-- verbatim. Section 3 is hand-added in the RM-02C1a manner, because the Prisma
-- DSL cannot express CHECK constraints or triggers: one CHECK per governance
-- rule, and the MON-03 append-only trigger pattern.

-- ── 1. enum + table ──────────────────────────────────────────────────────────

-- CreateEnum
CREATE TYPE "ResourceIdentityQuestionAction" AS ENUM ('TEACH', 'APPROVE', 'REJECT', 'SUPERSEDE', 'REVOKE');

-- CreateTable
CREATE TABLE "resource_identity_question_decisions" (
    "id" UUID NOT NULL,
    "workspaceId" UUID NOT NULL,
    "questionKey" VARCHAR(64) NOT NULL,
    "generation" INTEGER NOT NULL,
    "previousDecisionId" UUID,
    "action" "ResourceIdentityQuestionAction" NOT NULL,
    "selectedResourceCatalogId" UUID,
    "candidateContextDigest" TEXT,
    "resolutionPolicyVersion" TEXT,
    "originObservationId" UUID NOT NULL,
    "decidedByAccountId" UUID NOT NULL,
    "decidedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "reason" TEXT,

    CONSTRAINT "resource_identity_question_decisions_pkey" PRIMARY KEY ("id")
);

-- ── 2. indexes + foreign keys ────────────────────────────────────────────────

-- CreateIndex
CREATE INDEX "resource_identity_question_decisions_workspaceId_questionKe_idx" ON "resource_identity_question_decisions"("workspaceId", "questionKey", "generation" DESC);

-- CreateIndex
CREATE INDEX "resource_identity_question_decisions_selectedResourceCatalo_idx" ON "resource_identity_question_decisions"("selectedResourceCatalogId");

-- CreateIndex
CREATE INDEX "resource_identity_question_decisions_originObservationId_idx" ON "resource_identity_question_decisions"("originObservationId");

-- CreateIndex
CREATE UNIQUE INDEX "resource_identity_question_decisions_workspaceId_questionKe_key" ON "resource_identity_question_decisions"("workspaceId", "questionKey", "generation");

-- AddForeignKey
ALTER TABLE "resource_identity_question_decisions" ADD CONSTRAINT "resource_identity_question_decisions_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "resource_identity_question_decisions" ADD CONSTRAINT "resource_identity_question_decisions_previousDecisionId_fkey" FOREIGN KEY ("previousDecisionId") REFERENCES "resource_identity_question_decisions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "resource_identity_question_decisions" ADD CONSTRAINT "resource_identity_question_decisions_selectedResourceCatal_fkey" FOREIGN KEY ("selectedResourceCatalogId") REFERENCES "resource_catalogs"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "resource_identity_question_decisions" ADD CONSTRAINT "resource_identity_question_decisions_originObservationId_fkey" FOREIGN KEY ("originObservationId") REFERENCES "observed_resources"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "resource_identity_question_decisions" ADD CONSTRAINT "resource_identity_question_decisions_decidedByAccountId_fkey" FOREIGN KEY ("decidedByAccountId") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ── 3. governance rules the Prisma DSL cannot express (hand-added) ──────────

-- The ANSWER lives on exactly the events that carry one. APPROVE, REJECT and
-- REVOKE judge the answer of the event they follow; they state none of their own.
ALTER TABLE "resource_identity_question_decisions"
  ADD CONSTRAINT "iql01_selected_catalog_iff_answer" CHECK (
    ("action" IN ('TEACH', 'SUPERSEDE')) = ("selectedResourceCatalogId" IS NOT NULL)
  ),
  ADD CONSTRAINT "iql01_candidate_digest_iff_answer" CHECK (
    ("action" IN ('TEACH', 'SUPERSEDE')) = ("candidateContextDigest" IS NOT NULL)
  ),
  ADD CONSTRAINT "iql01_policy_version_iff_answer" CHECK (
    ("action" IN ('TEACH', 'SUPERSEDE')) = ("resolutionPolicyVersion" IS NOT NULL)
  ),
  -- A governance act that takes something away, or replaces it, says why.
  ADD CONSTRAINT "iql01_reason_required" CHECK (
    "action" NOT IN ('REJECT', 'SUPERSEDE', 'REVOKE')
    OR ("reason" IS NOT NULL AND length(btrim("reason")) > 0)
  ),
  -- Lineage: generation 1 has no predecessor, every later generation has one,
  -- and only a TEACH may begin a lineage.
  ADD CONSTRAINT "iql01_lineage" CHECK (
    "generation" >= 1
    AND ("generation" = 1) = ("previousDecisionId" IS NULL)
    AND ("action" = 'TEACH' OR "previousDecisionId" IS NOT NULL)
  );

-- APPEND-ONLY at the PostgreSQL boundary, the MON-03 pattern: history is never
-- rewritten or erased. A change of mind is the next generation, not an UPDATE.
CREATE FUNCTION reject_resource_identity_question_decision_mutation() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'IQL01_APPEND_ONLY: % is forbidden', TG_OP;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER resource_identity_question_decisions_immutable_trigger
BEFORE UPDATE OR DELETE ON "resource_identity_question_decisions"
FOR EACH ROW EXECUTE FUNCTION reject_resource_identity_question_decision_mutation();
